#!/usr/bin/env bash
#
# Shared helpers for the switchless DeepSeek V4.1 lifecycle scripts.
#
# Sourced, never executed. It loads and validates the topology, exposes
# per-rank getters, and provides the small remote-execution and logging
# primitives the other scripts share.

# shellcheck shell=bash

set -euo pipefail

LIB_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${LIB_DIR}/.." && pwd)"
TOPOLOGY_FILE="${TOPOLOGY_FILE:-${REPO_ROOT}/config/topology.env}"
ENV_FILE="${ENV_FILE:-${REPO_ROOT}/config/vllm.env}"
COMPOSE_FILE="${REPO_ROOT}/compose/compose.yaml"

# ---------------------------------------------------------------------------
# logging
# ---------------------------------------------------------------------------
log()  { printf '[%s] %s\n' "${SCRIPT_NAME:-lifecycle}" "$*"; }
warn() { printf '[%s] WARNING %s\n' "${SCRIPT_NAME:-lifecycle}" "$*" >&2; }
die()  { printf '[%s] ERROR %s\n' "${SCRIPT_NAME:-lifecycle}" "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# topology
# ---------------------------------------------------------------------------
load_topology() {
  [ -f "${TOPOLOGY_FILE}" ] || die "topology file not found: ${TOPOLOGY_FILE}"
  # shellcheck disable=SC1090
  . "${TOPOLOGY_FILE}"
  local rank
  for ((rank = 0; rank < NODE_COUNT; rank++)); do
    local prefix="RANK_${rank}_"
    local suffix
    for suffix in NAME SSH CONTROL_IP CONTROL_IFACE FABRIC; do
      local name="${prefix}${suffix}"
      [ -n "${!name:-}" ] || die "topology is missing ${name}"
    done
  done
}

validate_topology() {
  python3 "${LIB_DIR}/validate-topology.py" "${TOPOLOGY_FILE}"
}

rank_name()    { local n="$1"; local v="RANK_${n}_NAME";   printf '%s' "${!v}"; }
rank_ssh()     { local n="$1"; local v="RANK_${n}_SSH";    printf '%s' "${!v}"; }
rank_ctrl_ip() { local n="$1"; local v="RANK_${n}_CONTROL_IP";  printf '%s' "${!v}"; }
rank_iface()   { local n="$1"; local v="RANK_${n}_CONTROL_IFACE"; printf '%s' "${!v}"; }
rank_fabric()  { local n="$1"; local v="RANK_${n}_FABRIC"; printf '%s' "${!v}"; }

# Fabric entries in declared order: port0 lane a, port0 lane b, port1 lane a,
# port1 lane b. Index 2*port+lane.
rank_fabric_entry() {
  local rank="$1" index="$2"
  local raw
  raw="$(rank_fabric "${rank}")"
  local -a entries
  read -r -a entries <<< "${raw}"
  printf '%s' "${entries[${index}]}"
}

rank_port_addresses() {
  local rank="$1" port="$2" index
  for ((index = 0; index < 2; index++)); do
    local entry
    entry="$(rank_fabric_entry "${rank}" "$((port * 2 + index))")"
    printf '%s\n' "${entry#*:}"
  done
}

for_each_rank() {
  local rank
  for ((rank = 0; rank < NODE_COUNT; rank++)); do
    "$@" "${rank}"
  done
}

# ---------------------------------------------------------------------------
# remote execution
# ---------------------------------------------------------------------------
# Every remote command goes through the declared SSH destination with host-key
# checking and batch mode. Nothing here silently accepts an unknown host key;
# populate known_hosts first (see README).
# shellcheck disable=SC2086
rank_run() {
  local rank="$1"; shift
  ssh ${SSH_OPTS} -p "${SSH_PORT}" -o "ConnectTimeout=15" "$(rank_ssh "${rank}")" "$@"
}

# Run an arbitrary script fragment on a rank with the topology env available.
rank_run_script() {
  local rank="$1" script="$2"
  rank_run "${rank}" "bash -s" <<EOF
set -euo pipefail
${script}
EOF
}

# ---------------------------------------------------------------------------
# per-rank compose environment
# ---------------------------------------------------------------------------
# Emits the compose/.env content for one rank. Written on the target host so
# the same compose/compose.yaml is correct everywhere.
write_rank_env() {
  local rank="$1" head_rank="${2:-${HEAD_RANK}}"
  local headless_suffix=""
  local memory_slice="vllm-${CLUSTER_NAME}.slice"
  if [ "${rank}" -ne "${head_rank}" ]; then
    headless_suffix=" --headless"
  fi
  cat <<EOF
# Generated by scripts/start.sh from config/topology.env — do not edit by hand.
IMAGE=${IMAGE}
NODE_RANK=${rank}
MASTER_ADDR=$(rank_ctrl_ip "${head_rank}")
MASTER_PORT=${MASTER_PORT}
API_PORT=${API_PORT}
VLLM_HOST_IP=$(rank_ctrl_ip "${rank}")
CONTROL_IFACE=$(rank_iface "${rank}")
NCCL_IB_HCA=${NCCL_IB_HCA}
MEMORY_SLICE=${memory_slice}
MODEL_ROOT=${MODEL_ROOT}
WORKLOAD_ROOT=${WORKLOAD_ROOT}
CACHE_ROOT=${CACHE_ROOT}
ENGRAM_PATCH_DIR=${WORKLOAD_ROOT}/patches
CONTAINER_NAME=${CONTAINER_NAME}
HEADLESS_SUFFIX=${headless_suffix}
EOF
}

# ---------------------------------------------------------------------------
# health helpers (run on the head)
# ---------------------------------------------------------------------------
wait_for_head_api() {
  local rank="$1" deadline="${2:-3600}"
  local url="http://$(rank_ctrl_ip "${rank}"):${API_PORT}/health"
  local start now
  start="$(date +%s)"
  while :; do
    if rank_run "${rank}" "curl -fsS --max-time 10 '${url}'" >/dev/null 2>&1; then
      log "head API healthy at ${url}"
      return 0
    fi
    now="$(date +%s)"
    if [ "$((now - start))" -ge "${deadline}" ]; then
      die "head API did not become healthy within ${deadline}s (${url})"
    fi
    sleep 10
  done
}

wait_for_container_running() {
  local rank="$1" name="$2" deadline="${3:-600}"
  local start now
  start="$(date +%s)"
  while :; do
    if rank_run "${rank}" "docker inspect --format '{{.State.Running}}' '${name}'" 2>/dev/null | grep -qx true; then
      return 0
    fi
    now="$(date +%s)"
    if [ "$((now - start))" -ge "${deadline}" ]; then
      die "container ${name} on rank ${rank} did not start within ${deadline}s"
    fi
    sleep 5
  done
}

# ---------------------------------------------------------------------------
# checked local fence
# ---------------------------------------------------------------------------
# Stops ONLY the container that this project owns. The ownership labels are
# verified first (a same-named container from another project is refused, not
# stopped), the full container ID is resolved and only that ID is stopped, and
# on the head the rendezvous port must be free afterwards. Already-absent is
# idempotent success — but only after distinguishing absence from a Docker
# failure, which must never be reported as absence.
fence_rank() {
  local rank="$1"
  local head_marker="${2:-no}"
  local containment_slice="${3:-}"
  rank_run "${rank}" bash -s -- "${COMPOSE_PROJECT}" "${CONTAINER_NAME}" "${head_marker}" \
    "$(rank_ctrl_ip "${HEAD_RANK}")" "${MASTER_PORT}" "${containment_slice}" <<'REMOTE_FENCE'
set -euo pipefail
project="$1"; name="$2"; head_marker="$3"; head_ip="$4"; master_port="$5"; slice="$6"

if ! docker info >/dev/null 2>&1; then
  echo "FENCE_FAIL docker daemon is not reachable; absence cannot be assumed" >&2
  exit 1
fi

if ! docker inspect "${name}" >/dev/null 2>&1; then
  echo "FENCE_OK ${name} absent"
  exit 0
fi

observed_project="$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "${name}")"
observed_service="$(docker inspect --format '{{index .Config.Labels "com.docker.compose.service"}}' "${name}")"
if [ "${observed_project}" != "${project}" ] || [ "${observed_service}" != "vllm" ]; then
  echo "FENCE_FAIL ${name} belongs to project=${observed_project} service=${observed_service}, refusing to stop it" >&2
  exit 1
fi

full_id="$(docker inspect --format '{{.Id}}' "${name}")"
if [ "$(docker inspect --format '{{.State.Running}}' "${full_id}")" = "true" ]; then
  docker stop --timeout 90 "${full_id}" >/dev/null
  echo "FENCE_OK stopped ${full_id} (${observed_project}/vllm)"
else
  echo "FENCE_OK ${full_id} already stopped"
fi

# cgroup removal can lag the stop; wait briefly so the next start is not
# refused by the memory boundary still accounting for the old process.
if [ -n "${slice}" ]; then
  for _ in $(seq 1 30); do
    if ! docker inspect "${full_id}" >/dev/null 2>&1; then break; fi
    sleep 1
  done
fi

if [ "${head_marker}" = "yes" ]; then
  for _ in $(seq 1 30); do
    if ! ss -ltn 2>/dev/null | awk '{print $4}' | grep -q ":${master_port}\$"; then
      echo "FENCE_OK rendezvous tcp://${head_ip}:${master_port} is free"
      exit 0
    fi
    sleep 1
  done
  echo "FENCE_FAIL tcp://${head_ip}:${master_port} is still listening after the fence; an unexpected owner must be investigated, not killed" >&2
  exit 1
fi
REMOTE_FENCE
}
